name: Tests
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e git+https://github.com/PennyLaneAI/pennylane.git#egg=pennylane
          pip install -r requirements-ci.txt
          pip install wheel pytest pytest-cov pytest-mock pytest-benchmark flaky --upgrade

      - name: Install Plugin
        run: |
          python -m pip install --upgrade setuptools
          python setup.py bdist_wheel
          pip install dist/PennyLane*.whl

      - name: Run tests
        run: python -m pytest tests --cov=pennylane_aqt --cov-report=term-missing --cov-report=xml -p no:warnings --tb=native

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.codecov_token }}
          file: ./coverage.xml
