name: Tests
on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: blacksmith-2vcpu-ubuntu-2404  # ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13']

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e git+https://github.com/PennyLaneAI/pennylane.git#egg=pennylane
          pip install -r requirements-ci.txt
          pip install wheel pytest pytest-cov pytest-mock pytest-benchmark flaky --upgrade

      - name: Install Plugin
        run: |
          python -m pip install --upgrade setuptools>=75.8.1
          python setup.py bdist_wheel
          pip install dist/pennylane*.whl

      - name: Run tests
        run: python -m pytest tests --cov=pennylane_aqt --cov-report=term-missing --cov-report=xml -p no:warnings --tb=native

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.codecov_token }}
          file: ./coverage.xml
